# Generated by Django 2.0.6 on 2018-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_auto_20180616_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
