# Generated by Django 2.0.6 on 2018-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_auto_20180619_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, unique=True),
        ),
    ]
